### ISSUE TITLE
Feature: describe skusipolicy contents?

### ISSUE THREAD

**Issue by Wack0** [microsoft/secureboot_objects#43]
The readme states that this repo exists partially for transparency purposes.

Boot applications from th1+ that are vulnerable to baton drop were revoked by skusipolicy due to lack of dbx space.

skusipolicy is currently a single blob containing opaque hashes.

Are there any plans to also describe the contents of skusipolicy in this repository, or, if not that, then in some other location?

**Comment by Flickdm** [comment]
Hey @Wack0, thanks for the comment. This repo is meant for general purpose UEFI Secure Boot Objects and not Windows specific payloads. At this time we don't have plans to describe SkuSiPolicy here. The information we've shared publicly on SkuSiPolicy may be found [here](https://support.microsoft.com/en-us/topic/kb5027455-guidance-for-blocking-vulnerable-windows-boot-managers-522bb851-0a61-44ad-aa94-ad11119c5e91).
